stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - eoffice-v2
  before_script:
    - echo "before build eoffice-v2-backend"
  script:
    - >
      ssh -o StrictHostKeyChecking=no bit@192.168.4.18 "
      cd /home/bit/build-eoffice-v2/eoffice-backend ;
      chmod +x ./deployment/update.sh ;
      ./deployment/update.sh ;
      "
    - echo "eoffice-v2-backend Deployed"
  only:
    - main
